// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core`, `open_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

Future<void> initApp({required String appDataDir}) =>
    RustLib.instance.api.crateApiInitApp(appDataDir: appDataDir);

Future<void> shutdownApp() => RustLib.instance.api.crateApiShutdownApp();

Future<LibrarySourceStatus> checkLibrarySource() =>
    RustLib.instance.api.crateApiCheckLibrarySource();

Future<PlatformInt64> addLibrary({required String path}) =>
    RustLib.instance.api.crateApiAddLibrary(path: path);

Future<List<Library>> listLibraries() =>
    RustLib.instance.api.crateApiListLibraries();

Future<ScanSummary> scanLibraries() =>
    RustLib.instance.api.crateApiScanLibraries();

Future<bool> startScanLibraries() =>
    RustLib.instance.api.crateApiStartScanLibraries();

Future<LibraryScanStatus> getLibraryScanStatus() =>
    RustLib.instance.api.crateApiGetLibraryScanStatus();

Future<List<RawComic>> listLibraryComicsRaw({
  required SortBy sortBy,
  required SortDir sortDir,
}) => RustLib.instance.api.crateApiListLibraryComicsRaw(
  sortBy: sortBy,
  sortDir: sortDir,
);

Future<LibraryStorageStats> getLibraryStorageStats() =>
    RustLib.instance.api.crateApiGetLibraryStorageStats();

Future<List<String>> listComicsWithProgress() =>
    RustLib.instance.api.crateApiListComicsWithProgress();

Future<List<ReadingHistoryEntry>> listReadingHistory() =>
    RustLib.instance.api.crateApiListReadingHistory();

Future<List<RawChapter>> listComicChaptersRaw({
  required String comicSourcePath,
}) => RustLib.instance.api.crateApiListComicChaptersRaw(
  comicSourcePath: comicSourcePath,
);

Future<PlatformInt64> openChapterForReading({
  required OpenChapterPayload payload,
}) => RustLib.instance.api.crateApiOpenChapterForReading(payload: payload);

Future<ChapterContext?> getChapterContext({required PlatformInt64 chapterId}) =>
    RustLib.instance.api.crateApiGetChapterContext(chapterId: chapterId);

Future<List<PageInfo>> getChapterPages({required PlatformInt64 chapterId}) =>
    RustLib.instance.api.crateApiGetChapterPages(chapterId: chapterId);

Future<RenderedPage> renderPageVariant({required RenderPagePayload payload}) =>
    RustLib.instance.api.crateApiRenderPageVariant(payload: payload);

Future<void> prefetchPages({required PrefetchPagesPayload payload}) =>
    RustLib.instance.api.crateApiPrefetchPages(payload: payload);

Future<void> evictChapterPages({
  required PlatformInt64 chapterId,
  required List<int> keepPages,
}) => RustLib.instance.api.crateApiEvictChapterPages(
  chapterId: chapterId,
  keepPages: keepPages,
);

Future<void> saveProgress({required SaveProgressPayload payload}) =>
    RustLib.instance.api.crateApiSaveProgress(payload: payload);

Future<ReadingProgress?> getProgress({required PlatformInt64 chapterId}) =>
    RustLib.instance.api.crateApiGetProgress(chapterId: chapterId);

Future<List<Bookmark>> listBookmarks({required PlatformInt64 chapterId}) =>
    RustLib.instance.api.crateApiListBookmarks(chapterId: chapterId);

Future<PlatformInt64> addBookmark({required SaveBookmarkPayload payload}) =>
    RustLib.instance.api.crateApiAddBookmark(payload: payload);

Future<void> removeBookmark({required PlatformInt64 bookmarkId}) =>
    RustLib.instance.api.crateApiRemoveBookmark(bookmarkId: bookmarkId);

Future<List<ComicBookmark>> listAllBookmarks() =>
    RustLib.instance.api.crateApiListAllBookmarks();

Future<PlatformInt64> addComicBookmark({required String comicSourcePath}) =>
    RustLib.instance.api.crateApiAddComicBookmark(
      comicSourcePath: comicSourcePath,
    );

Future<void> removeComicBookmark({required String comicSourcePath}) => RustLib
    .instance
    .api
    .crateApiRemoveComicBookmark(comicSourcePath: comicSourcePath);

Future<bool> isComicBookmarked({required String comicSourcePath}) => RustLib
    .instance
    .api
    .crateApiIsComicBookmarked(comicSourcePath: comicSourcePath);

Future<PlatformInt64> addChapterFavorite({
  required String chapterSourcePath,
  required String comicSourcePath,
}) => RustLib.instance.api.crateApiAddChapterFavorite(
  chapterSourcePath: chapterSourcePath,
  comicSourcePath: comicSourcePath,
);

Future<void> removeChapterFavorite({required String chapterSourcePath}) =>
    RustLib.instance.api.crateApiRemoveChapterFavorite(
      chapterSourcePath: chapterSourcePath,
    );

Future<List<String>> listChapterFavorites({required String comicSourcePath}) =>
    RustLib.instance.api.crateApiListChapterFavorites(
      comicSourcePath: comicSourcePath,
    );

Future<List<SettingEntry>> listSettings() =>
    RustLib.instance.api.crateApiListSettings();

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiGetSetting(key: key);

Future<void> setSetting({required String key, required String valueJson}) =>
    RustLib.instance.api.crateApiSetSetting(key: key, valueJson: valueJson);

Future<void> exportDatabaseBackup({required String outputPath}) =>
    RustLib.instance.api.crateApiExportDatabaseBackup(outputPath: outputPath);

Future<void> importDatabaseBackup({required String inputPath}) =>
    RustLib.instance.api.crateApiImportDatabaseBackup(inputPath: inputPath);

Future<void> openContainingFolder({required String path}) =>
    RustLib.instance.api.crateApiOpenContainingFolder(path: path);

class Bookmark {
  final PlatformInt64 id;
  final PlatformInt64 chapterId;
  final PlatformInt64 page;
  final PlatformInt64 createdAt;
  final String note;

  const Bookmark({
    required this.id,
    required this.chapterId,
    required this.page,
    required this.createdAt,
    required this.note,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      chapterId.hashCode ^
      page.hashCode ^
      createdAt.hashCode ^
      note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bookmark &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          chapterId == other.chapterId &&
          page == other.page &&
          createdAt == other.createdAt &&
          note == other.note;
}

class ChapterContext {
  final PlatformInt64 chapterId;
  final PlatformInt64 comicId;
  final String comicSourcePath;
  final String chapterSourcePath;
  final String comicTitle;
  final String title;
  final PlatformInt64 chapterIndex;
  final PlatformInt64 chapterPosition;
  final PlatformInt64 chapterTotal;
  final PlatformInt64? prevChapterId;
  final String? prevChapterTitle;
  final PlatformInt64? nextChapterId;
  final String? nextChapterTitle;

  const ChapterContext({
    required this.chapterId,
    required this.comicId,
    required this.comicSourcePath,
    required this.chapterSourcePath,
    required this.comicTitle,
    required this.title,
    required this.chapterIndex,
    required this.chapterPosition,
    required this.chapterTotal,
    this.prevChapterId,
    this.prevChapterTitle,
    this.nextChapterId,
    this.nextChapterTitle,
  });

  @override
  int get hashCode =>
      chapterId.hashCode ^
      comicId.hashCode ^
      comicSourcePath.hashCode ^
      chapterSourcePath.hashCode ^
      comicTitle.hashCode ^
      title.hashCode ^
      chapterIndex.hashCode ^
      chapterPosition.hashCode ^
      chapterTotal.hashCode ^
      prevChapterId.hashCode ^
      prevChapterTitle.hashCode ^
      nextChapterId.hashCode ^
      nextChapterTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterContext &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          comicId == other.comicId &&
          comicSourcePath == other.comicSourcePath &&
          chapterSourcePath == other.chapterSourcePath &&
          comicTitle == other.comicTitle &&
          title == other.title &&
          chapterIndex == other.chapterIndex &&
          chapterPosition == other.chapterPosition &&
          chapterTotal == other.chapterTotal &&
          prevChapterId == other.prevChapterId &&
          prevChapterTitle == other.prevChapterTitle &&
          nextChapterId == other.nextChapterId &&
          nextChapterTitle == other.nextChapterTitle;
}

class ComicBookmark {
  final PlatformInt64 id;
  final String comicSourcePath;
  final String comicTitle;
  final PlatformInt64 createdAt;

  const ComicBookmark({
    required this.id,
    required this.comicSourcePath,
    required this.comicTitle,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      comicSourcePath.hashCode ^
      comicTitle.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComicBookmark &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          comicSourcePath == other.comicSourcePath &&
          comicTitle == other.comicTitle &&
          createdAt == other.createdAt;
}

class Library {
  final PlatformInt64 id;
  final String path;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const Library({
    required this.id,
    required this.path,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ path.hashCode ^ createdAt.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Library &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class LibraryScanStatus {
  final bool running;
  final PlatformInt64? startedAt;
  final PlatformInt64? finishedAt;
  final ScanSummary? lastSummary;
  final String? error;

  const LibraryScanStatus({
    required this.running,
    this.startedAt,
    this.finishedAt,
    this.lastSummary,
    this.error,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      startedAt.hashCode ^
      finishedAt.hashCode ^
      lastSummary.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryScanStatus &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          startedAt == other.startedAt &&
          finishedAt == other.finishedAt &&
          lastSummary == other.lastSummary &&
          error == other.error;
}

class LibrarySourceStatus {
  final bool configured;
  final String path;
  final bool exists;
  final bool isDir;
  final bool readable;
  final String? error;

  const LibrarySourceStatus({
    required this.configured,
    required this.path,
    required this.exists,
    required this.isDir,
    required this.readable,
    this.error,
  });

  @override
  int get hashCode =>
      configured.hashCode ^
      path.hashCode ^
      exists.hashCode ^
      isDir.hashCode ^
      readable.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibrarySourceStatus &&
          runtimeType == other.runtimeType &&
          configured == other.configured &&
          path == other.path &&
          exists == other.exists &&
          isDir == other.isDir &&
          readable == other.readable &&
          error == other.error;
}

class LibraryStorageStats {
  final PlatformInt64 totalSizeBytes;
  final PlatformInt64 comicCount;

  const LibraryStorageStats({
    required this.totalSizeBytes,
    required this.comicCount,
  });

  static Future<LibraryStorageStats> default_() =>
      RustLib.instance.api.crateApiLibraryStorageStatsDefault();

  @override
  int get hashCode => totalSizeBytes.hashCode ^ comicCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryStorageStats &&
          runtimeType == other.runtimeType &&
          totalSizeBytes == other.totalSizeBytes &&
          comicCount == other.comicCount;
}

class OpenChapterPayload {
  final String comicSourcePath;
  final String chapterSourcePath;

  const OpenChapterPayload({
    required this.comicSourcePath,
    required this.chapterSourcePath,
  });

  @override
  int get hashCode => comicSourcePath.hashCode ^ chapterSourcePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenChapterPayload &&
          runtimeType == other.runtimeType &&
          comicSourcePath == other.comicSourcePath &&
          chapterSourcePath == other.chapterSourcePath;
}

class PageInfo {
  final int index;
  final String name;
  final int? width;
  final int? height;

  const PageInfo({
    required this.index,
    required this.name,
    this.width,
    this.height,
  });

  @override
  int get hashCode =>
      index.hashCode ^ name.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          width == other.width &&
          height == other.height;
}

class PrefetchPagesPayload {
  final PlatformInt64 chapterId;
  final Uint32List pageIndices;

  const PrefetchPagesPayload({
    required this.chapterId,
    required this.pageIndices,
  });

  @override
  int get hashCode => chapterId.hashCode ^ pageIndices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrefetchPagesPayload &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          pageIndices == other.pageIndices;
}

class RawChapter {
  final String title;
  final PlatformInt64 chapterIndex;
  final String sourcePath;
  final String sourceType;
  final PlatformInt64 dateModified;
  final PlatformInt64 pageCount;
  final bool isRead;
  final PlatformInt64 lastPage;
  final PlatformInt64 totalPages;
  final PlatformInt64 sizeBytes;

  const RawChapter({
    required this.title,
    required this.chapterIndex,
    required this.sourcePath,
    required this.sourceType,
    required this.dateModified,
    required this.pageCount,
    required this.isRead,
    required this.lastPage,
    required this.totalPages,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      chapterIndex.hashCode ^
      sourcePath.hashCode ^
      sourceType.hashCode ^
      dateModified.hashCode ^
      pageCount.hashCode ^
      isRead.hashCode ^
      lastPage.hashCode ^
      totalPages.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawChapter &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          chapterIndex == other.chapterIndex &&
          sourcePath == other.sourcePath &&
          sourceType == other.sourceType &&
          dateModified == other.dateModified &&
          pageCount == other.pageCount &&
          isRead == other.isRead &&
          lastPage == other.lastPage &&
          totalPages == other.totalPages &&
          sizeBytes == other.sizeBytes;
}

class RawComic {
  final String title;
  final String sourcePath;
  final String sourceType;
  final PlatformInt64 dateModified;
  final PlatformInt64 chapterCount;
  final PlatformInt64 readChapterCount;
  final PlatformInt64 inProgressChapterCount;
  final PlatformInt64 sizeBytes;

  const RawComic({
    required this.title,
    required this.sourcePath,
    required this.sourceType,
    required this.dateModified,
    required this.chapterCount,
    required this.readChapterCount,
    required this.inProgressChapterCount,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      sourcePath.hashCode ^
      sourceType.hashCode ^
      dateModified.hashCode ^
      chapterCount.hashCode ^
      readChapterCount.hashCode ^
      inProgressChapterCount.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawComic &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          sourcePath == other.sourcePath &&
          sourceType == other.sourceType &&
          dateModified == other.dateModified &&
          chapterCount == other.chapterCount &&
          readChapterCount == other.readChapterCount &&
          inProgressChapterCount == other.inProgressChapterCount &&
          sizeBytes == other.sizeBytes;
}

class ReadingHistoryEntry {
  final String comicSourcePath;
  final String comicTitle;
  final String chapterTitle;
  final String chapterSourcePath;
  final PlatformInt64 chapterId;
  final PlatformInt64 lastPage;
  final PlatformInt64 totalPages;
  final bool isRead;
  final PlatformInt64 updatedAt;

  const ReadingHistoryEntry({
    required this.comicSourcePath,
    required this.comicTitle,
    required this.chapterTitle,
    required this.chapterSourcePath,
    required this.chapterId,
    required this.lastPage,
    required this.totalPages,
    required this.isRead,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      comicSourcePath.hashCode ^
      comicTitle.hashCode ^
      chapterTitle.hashCode ^
      chapterSourcePath.hashCode ^
      chapterId.hashCode ^
      lastPage.hashCode ^
      totalPages.hashCode ^
      isRead.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingHistoryEntry &&
          runtimeType == other.runtimeType &&
          comicSourcePath == other.comicSourcePath &&
          comicTitle == other.comicTitle &&
          chapterTitle == other.chapterTitle &&
          chapterSourcePath == other.chapterSourcePath &&
          chapterId == other.chapterId &&
          lastPage == other.lastPage &&
          totalPages == other.totalPages &&
          isRead == other.isRead &&
          updatedAt == other.updatedAt;
}

class ReadingProgress {
  final PlatformInt64 chapterId;
  final PlatformInt64 lastPage;
  final PlatformInt64 totalPages;
  final bool isRead;

  const ReadingProgress({
    required this.chapterId,
    required this.lastPage,
    required this.totalPages,
    required this.isRead,
  });

  @override
  int get hashCode =>
      chapterId.hashCode ^
      lastPage.hashCode ^
      totalPages.hashCode ^
      isRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadingProgress &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          lastPage == other.lastPage &&
          totalPages == other.totalPages &&
          isRead == other.isRead;
}

class RenderPagePayload {
  final PlatformInt64 chapterId;
  final int pageIndex;

  const RenderPagePayload({required this.chapterId, required this.pageIndex});

  @override
  int get hashCode => chapterId.hashCode ^ pageIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderPagePayload &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          pageIndex == other.pageIndex;
}

class RenderedPage {
  final Uint8List bytes;
  final String mime;
  final int width;
  final int height;

  const RenderedPage({
    required this.bytes,
    required this.mime,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^ mime.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderedPage &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          mime == other.mime &&
          width == other.width &&
          height == other.height;
}

class SaveBookmarkPayload {
  final PlatformInt64 chapterId;
  final PlatformInt64 page;
  final String? note;

  const SaveBookmarkPayload({
    required this.chapterId,
    required this.page,
    this.note,
  });

  @override
  int get hashCode => chapterId.hashCode ^ page.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveBookmarkPayload &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          page == other.page &&
          note == other.note;
}

class SaveProgressPayload {
  final PlatformInt64 chapterId;
  final PlatformInt64 lastPage;
  final PlatformInt64 totalPages;
  final bool isRead;

  const SaveProgressPayload({
    required this.chapterId,
    required this.lastPage,
    required this.totalPages,
    required this.isRead,
  });

  @override
  int get hashCode =>
      chapterId.hashCode ^
      lastPage.hashCode ^
      totalPages.hashCode ^
      isRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveProgressPayload &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          lastPage == other.lastPage &&
          totalPages == other.totalPages &&
          isRead == other.isRead;
}

class ScanSummary {
  final int comics;
  final int chapters;

  const ScanSummary({required this.comics, required this.chapters});

  @override
  int get hashCode => comics.hashCode ^ chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanSummary &&
          runtimeType == other.runtimeType &&
          comics == other.comics &&
          chapters == other.chapters;
}

class SettingEntry {
  final String key;
  final String valueJson;

  const SettingEntry({required this.key, required this.valueJson});

  @override
  int get hashCode => key.hashCode ^ valueJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          valueJson == other.valueJson;
}

enum SortBy { name, folderDate }

enum SortDir { asc, desc }
