// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Bookmark dco_decode_bookmark(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ChapterContext dco_decode_box_autoadd_chapter_context(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  OpenChapterPayload dco_decode_box_autoadd_open_chapter_payload(dynamic raw);

  @protected
  PrefetchPagesPayload dco_decode_box_autoadd_prefetch_pages_payload(
    dynamic raw,
  );

  @protected
  ReadingProgress dco_decode_box_autoadd_reading_progress(dynamic raw);

  @protected
  RenderPagePayload dco_decode_box_autoadd_render_page_payload(dynamic raw);

  @protected
  SaveBookmarkPayload dco_decode_box_autoadd_save_bookmark_payload(dynamic raw);

  @protected
  SaveProgressPayload dco_decode_box_autoadd_save_progress_payload(dynamic raw);

  @protected
  ScanSummary dco_decode_box_autoadd_scan_summary(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ChapterContext dco_decode_chapter_context(dynamic raw);

  @protected
  ComicBookmark dco_decode_comic_bookmark(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Library dco_decode_library(dynamic raw);

  @protected
  LibraryScanStatus dco_decode_library_scan_status(dynamic raw);

  @protected
  LibrarySourceStatus dco_decode_library_source_status(dynamic raw);

  @protected
  LibraryStorageStats dco_decode_library_storage_stats(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Bookmark> dco_decode_list_bookmark(dynamic raw);

  @protected
  List<ComicBookmark> dco_decode_list_comic_bookmark(dynamic raw);

  @protected
  List<Library> dco_decode_list_library(dynamic raw);

  @protected
  List<PageInfo> dco_decode_list_page_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RawChapter> dco_decode_list_raw_chapter(dynamic raw);

  @protected
  List<RawComic> dco_decode_list_raw_comic(dynamic raw);

  @protected
  List<ReadingHistoryEntry> dco_decode_list_reading_history_entry(dynamic raw);

  @protected
  List<SettingEntry> dco_decode_list_setting_entry(dynamic raw);

  @protected
  OpenChapterPayload dco_decode_open_chapter_payload(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ChapterContext? dco_decode_opt_box_autoadd_chapter_context(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ReadingProgress? dco_decode_opt_box_autoadd_reading_progress(dynamic raw);

  @protected
  ScanSummary? dco_decode_opt_box_autoadd_scan_summary(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PageInfo dco_decode_page_info(dynamic raw);

  @protected
  PrefetchPagesPayload dco_decode_prefetch_pages_payload(dynamic raw);

  @protected
  RawChapter dco_decode_raw_chapter(dynamic raw);

  @protected
  RawComic dco_decode_raw_comic(dynamic raw);

  @protected
  ReadingHistoryEntry dco_decode_reading_history_entry(dynamic raw);

  @protected
  ReadingProgress dco_decode_reading_progress(dynamic raw);

  @protected
  RenderPagePayload dco_decode_render_page_payload(dynamic raw);

  @protected
  RenderedPage dco_decode_rendered_page(dynamic raw);

  @protected
  SaveBookmarkPayload dco_decode_save_bookmark_payload(dynamic raw);

  @protected
  SaveProgressPayload dco_decode_save_progress_payload(dynamic raw);

  @protected
  ScanSummary dco_decode_scan_summary(dynamic raw);

  @protected
  SettingEntry dco_decode_setting_entry(dynamic raw);

  @protected
  SortBy dco_decode_sort_by(dynamic raw);

  @protected
  SortDir dco_decode_sort_dir(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Bookmark sse_decode_bookmark(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ChapterContext sse_decode_box_autoadd_chapter_context(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  OpenChapterPayload sse_decode_box_autoadd_open_chapter_payload(
    SseDeserializer deserializer,
  );

  @protected
  PrefetchPagesPayload sse_decode_box_autoadd_prefetch_pages_payload(
    SseDeserializer deserializer,
  );

  @protected
  ReadingProgress sse_decode_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  RenderPagePayload sse_decode_box_autoadd_render_page_payload(
    SseDeserializer deserializer,
  );

  @protected
  SaveBookmarkPayload sse_decode_box_autoadd_save_bookmark_payload(
    SseDeserializer deserializer,
  );

  @protected
  SaveProgressPayload sse_decode_box_autoadd_save_progress_payload(
    SseDeserializer deserializer,
  );

  @protected
  ScanSummary sse_decode_box_autoadd_scan_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ChapterContext sse_decode_chapter_context(SseDeserializer deserializer);

  @protected
  ComicBookmark sse_decode_comic_bookmark(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Library sse_decode_library(SseDeserializer deserializer);

  @protected
  LibraryScanStatus sse_decode_library_scan_status(
    SseDeserializer deserializer,
  );

  @protected
  LibrarySourceStatus sse_decode_library_source_status(
    SseDeserializer deserializer,
  );

  @protected
  LibraryStorageStats sse_decode_library_storage_stats(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Bookmark> sse_decode_list_bookmark(SseDeserializer deserializer);

  @protected
  List<ComicBookmark> sse_decode_list_comic_bookmark(
    SseDeserializer deserializer,
  );

  @protected
  List<Library> sse_decode_list_library(SseDeserializer deserializer);

  @protected
  List<PageInfo> sse_decode_list_page_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RawChapter> sse_decode_list_raw_chapter(SseDeserializer deserializer);

  @protected
  List<RawComic> sse_decode_list_raw_comic(SseDeserializer deserializer);

  @protected
  List<ReadingHistoryEntry> sse_decode_list_reading_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<SettingEntry> sse_decode_list_setting_entry(
    SseDeserializer deserializer,
  );

  @protected
  OpenChapterPayload sse_decode_open_chapter_payload(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ChapterContext? sse_decode_opt_box_autoadd_chapter_context(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ReadingProgress? sse_decode_opt_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  );

  @protected
  ScanSummary? sse_decode_opt_box_autoadd_scan_summary(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PageInfo sse_decode_page_info(SseDeserializer deserializer);

  @protected
  PrefetchPagesPayload sse_decode_prefetch_pages_payload(
    SseDeserializer deserializer,
  );

  @protected
  RawChapter sse_decode_raw_chapter(SseDeserializer deserializer);

  @protected
  RawComic sse_decode_raw_comic(SseDeserializer deserializer);

  @protected
  ReadingHistoryEntry sse_decode_reading_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  ReadingProgress sse_decode_reading_progress(SseDeserializer deserializer);

  @protected
  RenderPagePayload sse_decode_render_page_payload(
    SseDeserializer deserializer,
  );

  @protected
  RenderedPage sse_decode_rendered_page(SseDeserializer deserializer);

  @protected
  SaveBookmarkPayload sse_decode_save_bookmark_payload(
    SseDeserializer deserializer,
  );

  @protected
  SaveProgressPayload sse_decode_save_progress_payload(
    SseDeserializer deserializer,
  );

  @protected
  ScanSummary sse_decode_scan_summary(SseDeserializer deserializer);

  @protected
  SettingEntry sse_decode_setting_entry(SseDeserializer deserializer);

  @protected
  SortBy sse_decode_sort_by(SseDeserializer deserializer);

  @protected
  SortDir sse_decode_sort_dir(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bookmark(Bookmark self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chapter_context(
    ChapterContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_open_chapter_payload(
    OpenChapterPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_prefetch_pages_payload(
    PrefetchPagesPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_render_page_payload(
    RenderPagePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_save_bookmark_payload(
    SaveBookmarkPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_save_progress_payload(
    SaveProgressPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scan_summary(
    ScanSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_context(
    ChapterContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comic_bookmark(ComicBookmark self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library(Library self, SseSerializer serializer);

  @protected
  void sse_encode_library_scan_status(
    LibraryScanStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_source_status(
    LibrarySourceStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_library_storage_stats(
    LibraryStorageStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bookmark(List<Bookmark> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comic_bookmark(
    List<ComicBookmark> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library(List<Library> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page_info(List<PageInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_raw_chapter(
    List<RawChapter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_raw_comic(List<RawComic> self, SseSerializer serializer);

  @protected
  void sse_encode_list_reading_history_entry(
    List<ReadingHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_setting_entry(
    List<SettingEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_open_chapter_payload(
    OpenChapterPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_chapter_context(
    ChapterContext? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reading_progress(
    ReadingProgress? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_scan_summary(
    ScanSummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_page_info(PageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_prefetch_pages_payload(
    PrefetchPagesPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_raw_chapter(RawChapter self, SseSerializer serializer);

  @protected
  void sse_encode_raw_comic(RawComic self, SseSerializer serializer);

  @protected
  void sse_encode_reading_history_entry(
    ReadingHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_render_page_payload(
    RenderPagePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rendered_page(RenderedPage self, SseSerializer serializer);

  @protected
  void sse_encode_save_bookmark_payload(
    SaveBookmarkPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_save_progress_payload(
    SaveProgressPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_summary(ScanSummary self, SseSerializer serializer);

  @protected
  void sse_encode_setting_entry(SettingEntry self, SseSerializer serializer);

  @protected
  void sse_encode_sort_by(SortBy self, SseSerializer serializer);

  @protected
  void sse_encode_sort_dir(SortDir self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
