// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1118463050;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'comicrd_bridge',
        ioDirectory: '../crates/comicrd_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PlatformInt64> crateApiAddBookmark({
    required SaveBookmarkPayload payload,
  });

  Future<PlatformInt64> crateApiAddChapterFavorite({
    required String chapterSourcePath,
    required String comicSourcePath,
  });

  Future<PlatformInt64> crateApiAddComicBookmark({
    required String comicSourcePath,
  });

  Future<PlatformInt64> crateApiAddLibrary({required String path});

  Future<LibrarySourceStatus> crateApiCheckLibrarySource();

  Future<void> crateApiEvictChapterPages({
    required PlatformInt64 chapterId,
    required List<int> keepPages,
  });

  Future<void> crateApiExportDatabaseBackup({required String outputPath});

  Future<ChapterContext?> crateApiGetChapterContext({
    required PlatformInt64 chapterId,
  });

  Future<List<PageInfo>> crateApiGetChapterPages({
    required PlatformInt64 chapterId,
  });

  Future<Uint8List> crateApiGetComicThumbnail({
    required String sourcePath,
    required int maxWidth,
    required int maxHeight,
  });

  Future<LibraryScanStatus> crateApiGetLibraryScanStatus();

  Future<LibraryStorageStats> crateApiGetLibraryStorageStats();

  Future<ReadingProgress?> crateApiGetProgress({
    required PlatformInt64 chapterId,
  });

  Future<String?> crateApiGetSetting({required String key});

  Future<void> crateApiImportDatabaseBackup({required String inputPath});

  Future<void> crateApiInitApp({required String appDataDir});

  Future<bool> crateApiIsComicBookmarked({required String comicSourcePath});

  Future<LibraryStorageStats> crateApiLibraryStorageStatsDefault();

  Future<List<ComicBookmark>> crateApiListAllBookmarks();

  Future<List<Bookmark>> crateApiListBookmarks({
    required PlatformInt64 chapterId,
  });

  Future<List<String>> crateApiListChapterFavorites({
    required String comicSourcePath,
  });

  Future<List<RawChapter>> crateApiListComicChaptersRaw({
    required String comicSourcePath,
  });

  Future<List<String>> crateApiListComicsWithProgress();

  Future<List<Library>> crateApiListLibraries();

  Future<List<RawComic>> crateApiListLibraryComicsRaw({
    required SortBy sortBy,
    required SortDir sortDir,
  });

  Future<List<ReadingHistoryEntry>> crateApiListReadingHistory();

  Future<List<SettingEntry>> crateApiListSettings();

  Future<PlatformInt64> crateApiOpenChapterForReading({
    required OpenChapterPayload payload,
  });

  Future<void> crateApiOpenContainingFolder({required String path});

  Future<void> crateApiPrefetchPages({required PrefetchPagesPayload payload});

  Future<void> crateApiRemoveBookmark({required PlatformInt64 bookmarkId});

  Future<void> crateApiRemoveChapterFavorite({
    required String chapterSourcePath,
  });

  Future<void> crateApiRemoveComicBookmark({required String comicSourcePath});

  Future<RenderedPage> crateApiRenderPageVariant({
    required RenderPagePayload payload,
  });

  Future<void> crateApiSaveProgress({required SaveProgressPayload payload});

  Future<ScanSummary> crateApiScanLibraries();

  Future<void> crateApiSetSetting({
    required String key,
    required String valueJson,
  });

  Future<void> crateApiShutdownApp();

  Future<bool> crateApiStartScanLibraries();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlatformInt64> crateApiAddBookmark({
    required SaveBookmarkPayload payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_save_bookmark_payload(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAddBookmarkConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddBookmarkConstMeta =>
      const TaskConstMeta(debugName: "add_bookmark", argNames: ["payload"]);

  @override
  Future<PlatformInt64> crateApiAddChapterFavorite({
    required String chapterSourcePath,
    required String comicSourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chapterSourcePath, serializer);
          sse_encode_String(comicSourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAddChapterFavoriteConstMeta,
        argValues: [chapterSourcePath, comicSourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddChapterFavoriteConstMeta => const TaskConstMeta(
    debugName: "add_chapter_favorite",
    argNames: ["chapterSourcePath", "comicSourcePath"],
  );

  @override
  Future<PlatformInt64> crateApiAddComicBookmark({
    required String comicSourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicSourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAddComicBookmarkConstMeta,
        argValues: [comicSourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddComicBookmarkConstMeta => const TaskConstMeta(
    debugName: "add_comic_bookmark",
    argNames: ["comicSourcePath"],
  );

  @override
  Future<PlatformInt64> crateApiAddLibrary({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAddLibraryConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddLibraryConstMeta =>
      const TaskConstMeta(debugName: "add_library", argNames: ["path"]);

  @override
  Future<LibrarySourceStatus> crateApiCheckLibrarySource() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_source_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCheckLibrarySourceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCheckLibrarySourceConstMeta =>
      const TaskConstMeta(debugName: "check_library_source", argNames: []);

  @override
  Future<void> crateApiEvictChapterPages({
    required PlatformInt64 chapterId,
    required List<int> keepPages,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(chapterId, serializer);
          sse_encode_list_prim_u_32_loose(keepPages, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEvictChapterPagesConstMeta,
        argValues: [chapterId, keepPages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEvictChapterPagesConstMeta => const TaskConstMeta(
    debugName: "evict_chapter_pages",
    argNames: ["chapterId", "keepPages"],
  );

  @override
  Future<void> crateApiExportDatabaseBackup({required String outputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportDatabaseBackupConstMeta,
        argValues: [outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportDatabaseBackupConstMeta =>
      const TaskConstMeta(
        debugName: "export_database_backup",
        argNames: ["outputPath"],
      );

  @override
  Future<ChapterContext?> crateApiGetChapterContext({
    required PlatformInt64 chapterId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(chapterId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_chapter_context,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetChapterContextConstMeta,
        argValues: [chapterId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetChapterContextConstMeta => const TaskConstMeta(
    debugName: "get_chapter_context",
    argNames: ["chapterId"],
  );

  @override
  Future<List<PageInfo>> crateApiGetChapterPages({
    required PlatformInt64 chapterId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(chapterId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_page_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetChapterPagesConstMeta,
        argValues: [chapterId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetChapterPagesConstMeta => const TaskConstMeta(
    debugName: "get_chapter_pages",
    argNames: ["chapterId"],
  );

  @override
  Future<Uint8List> crateApiGetComicThumbnail({
    required String sourcePath,
    required int maxWidth,
    required int maxHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sourcePath, serializer);
          sse_encode_u_32(maxWidth, serializer);
          sse_encode_u_32(maxHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetComicThumbnailConstMeta,
        argValues: [sourcePath, maxWidth, maxHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetComicThumbnailConstMeta => const TaskConstMeta(
    debugName: "get_comic_thumbnail",
    argNames: ["sourcePath", "maxWidth", "maxHeight"],
  );

  @override
  Future<LibraryScanStatus> crateApiGetLibraryScanStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_scan_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetLibraryScanStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLibraryScanStatusConstMeta =>
      const TaskConstMeta(debugName: "get_library_scan_status", argNames: []);

  @override
  Future<LibraryStorageStats> crateApiGetLibraryStorageStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_storage_stats,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetLibraryStorageStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLibraryStorageStatsConstMeta =>
      const TaskConstMeta(debugName: "get_library_storage_stats", argNames: []);

  @override
  Future<ReadingProgress?> crateApiGetProgress({
    required PlatformInt64 chapterId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(chapterId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_reading_progress,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetProgressConstMeta,
        argValues: [chapterId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetProgressConstMeta =>
      const TaskConstMeta(debugName: "get_progress", argNames: ["chapterId"]);

  @override
  Future<String?> crateApiGetSetting({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetSettingConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSettingConstMeta =>
      const TaskConstMeta(debugName: "get_setting", argNames: ["key"]);

  @override
  Future<void> crateApiImportDatabaseBackup({required String inputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImportDatabaseBackupConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportDatabaseBackupConstMeta =>
      const TaskConstMeta(
        debugName: "import_database_backup",
        argNames: ["inputPath"],
      );

  @override
  Future<void> crateApiInitApp({required String appDataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(appDataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [appDataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: ["appDataDir"]);

  @override
  Future<bool> crateApiIsComicBookmarked({required String comicSourcePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicSourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIsComicBookmarkedConstMeta,
        argValues: [comicSourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsComicBookmarkedConstMeta => const TaskConstMeta(
    debugName: "is_comic_bookmarked",
    argNames: ["comicSourcePath"],
  );

  @override
  Future<LibraryStorageStats> crateApiLibraryStorageStatsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_storage_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryStorageStatsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryStorageStatsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "library_storage_stats_default",
        argNames: [],
      );

  @override
  Future<List<ComicBookmark>> crateApiListAllBookmarks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_comic_bookmark,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListAllBookmarksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListAllBookmarksConstMeta =>
      const TaskConstMeta(debugName: "list_all_bookmarks", argNames: []);

  @override
  Future<List<Bookmark>> crateApiListBookmarks({
    required PlatformInt64 chapterId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(chapterId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bookmark,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListBookmarksConstMeta,
        argValues: [chapterId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListBookmarksConstMeta =>
      const TaskConstMeta(debugName: "list_bookmarks", argNames: ["chapterId"]);

  @override
  Future<List<String>> crateApiListChapterFavorites({
    required String comicSourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicSourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListChapterFavoritesConstMeta,
        argValues: [comicSourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListChapterFavoritesConstMeta =>
      const TaskConstMeta(
        debugName: "list_chapter_favorites",
        argNames: ["comicSourcePath"],
      );

  @override
  Future<List<RawChapter>> crateApiListComicChaptersRaw({
    required String comicSourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicSourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_raw_chapter,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListComicChaptersRawConstMeta,
        argValues: [comicSourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListComicChaptersRawConstMeta =>
      const TaskConstMeta(
        debugName: "list_comic_chapters_raw",
        argNames: ["comicSourcePath"],
      );

  @override
  Future<List<String>> crateApiListComicsWithProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListComicsWithProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListComicsWithProgressConstMeta =>
      const TaskConstMeta(debugName: "list_comics_with_progress", argNames: []);

  @override
  Future<List<Library>> crateApiListLibraries() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_library,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListLibrariesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListLibrariesConstMeta =>
      const TaskConstMeta(debugName: "list_libraries", argNames: []);

  @override
  Future<List<RawComic>> crateApiListLibraryComicsRaw({
    required SortBy sortBy,
    required SortDir sortDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_sort_by(sortBy, serializer);
          sse_encode_sort_dir(sortDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_raw_comic,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListLibraryComicsRawConstMeta,
        argValues: [sortBy, sortDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListLibraryComicsRawConstMeta =>
      const TaskConstMeta(
        debugName: "list_library_comics_raw",
        argNames: ["sortBy", "sortDir"],
      );

  @override
  Future<List<ReadingHistoryEntry>> crateApiListReadingHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_reading_history_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListReadingHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListReadingHistoryConstMeta =>
      const TaskConstMeta(debugName: "list_reading_history", argNames: []);

  @override
  Future<List<SettingEntry>> crateApiListSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_setting_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListSettingsConstMeta =>
      const TaskConstMeta(debugName: "list_settings", argNames: []);

  @override
  Future<PlatformInt64> crateApiOpenChapterForReading({
    required OpenChapterPayload payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_open_chapter_payload(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpenChapterForReadingConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenChapterForReadingConstMeta =>
      const TaskConstMeta(
        debugName: "open_chapter_for_reading",
        argNames: ["payload"],
      );

  @override
  Future<void> crateApiOpenContainingFolder({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiOpenContainingFolderConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenContainingFolderConstMeta =>
      const TaskConstMeta(
        debugName: "open_containing_folder",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiPrefetchPages({required PrefetchPagesPayload payload}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_prefetch_pages_payload(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPrefetchPagesConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrefetchPagesConstMeta =>
      const TaskConstMeta(debugName: "prefetch_pages", argNames: ["payload"]);

  @override
  Future<void> crateApiRemoveBookmark({required PlatformInt64 bookmarkId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(bookmarkId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRemoveBookmarkConstMeta,
        argValues: [bookmarkId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoveBookmarkConstMeta => const TaskConstMeta(
    debugName: "remove_bookmark",
    argNames: ["bookmarkId"],
  );

  @override
  Future<void> crateApiRemoveChapterFavorite({
    required String chapterSourcePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chapterSourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRemoveChapterFavoriteConstMeta,
        argValues: [chapterSourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoveChapterFavoriteConstMeta =>
      const TaskConstMeta(
        debugName: "remove_chapter_favorite",
        argNames: ["chapterSourcePath"],
      );

  @override
  Future<void> crateApiRemoveComicBookmark({required String comicSourcePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(comicSourcePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRemoveComicBookmarkConstMeta,
        argValues: [comicSourcePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoveComicBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "remove_comic_bookmark",
        argNames: ["comicSourcePath"],
      );

  @override
  Future<RenderedPage> crateApiRenderPageVariant({
    required RenderPagePayload payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_render_page_payload(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rendered_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRenderPageVariantConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRenderPageVariantConstMeta => const TaskConstMeta(
    debugName: "render_page_variant",
    argNames: ["payload"],
  );

  @override
  Future<void> crateApiSaveProgress({required SaveProgressPayload payload}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_save_progress_payload(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveProgressConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveProgressConstMeta =>
      const TaskConstMeta(debugName: "save_progress", argNames: ["payload"]);

  @override
  Future<ScanSummary> crateApiScanLibraries() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scan_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScanLibrariesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanLibrariesConstMeta =>
      const TaskConstMeta(debugName: "scan_libraries", argNames: []);

  @override
  Future<void> crateApiSetSetting({
    required String key,
    required String valueJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(valueJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetSettingConstMeta,
        argValues: [key, valueJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetSettingConstMeta => const TaskConstMeta(
    debugName: "set_setting",
    argNames: ["key", "valueJson"],
  );

  @override
  Future<void> crateApiShutdownApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiShutdownAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiShutdownAppConstMeta =>
      const TaskConstMeta(debugName: "shutdown_app", argNames: []);

  @override
  Future<bool> crateApiStartScanLibraries() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStartScanLibrariesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartScanLibrariesConstMeta =>
      const TaskConstMeta(debugName: "start_scan_libraries", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Bookmark dco_decode_bookmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Bookmark(
      id: dco_decode_i_64(arr[0]),
      chapterId: dco_decode_i_64(arr[1]),
      page: dco_decode_i_64(arr[2]),
      createdAt: dco_decode_i_64(arr[3]),
      note: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChapterContext dco_decode_box_autoadd_chapter_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_chapter_context(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  OpenChapterPayload dco_decode_box_autoadd_open_chapter_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_open_chapter_payload(raw);
  }

  @protected
  PrefetchPagesPayload dco_decode_box_autoadd_prefetch_pages_payload(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_prefetch_pages_payload(raw);
  }

  @protected
  ReadingProgress dco_decode_box_autoadd_reading_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_reading_progress(raw);
  }

  @protected
  RenderPagePayload dco_decode_box_autoadd_render_page_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_render_page_payload(raw);
  }

  @protected
  SaveBookmarkPayload dco_decode_box_autoadd_save_bookmark_payload(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_save_bookmark_payload(raw);
  }

  @protected
  SaveProgressPayload dco_decode_box_autoadd_save_progress_payload(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_save_progress_payload(raw);
  }

  @protected
  ScanSummary dco_decode_box_autoadd_scan_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scan_summary(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ChapterContext dco_decode_chapter_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return ChapterContext(
      chapterId: dco_decode_i_64(arr[0]),
      comicId: dco_decode_i_64(arr[1]),
      comicSourcePath: dco_decode_String(arr[2]),
      chapterSourcePath: dco_decode_String(arr[3]),
      comicTitle: dco_decode_String(arr[4]),
      title: dco_decode_String(arr[5]),
      chapterIndex: dco_decode_i_64(arr[6]),
      chapterPosition: dco_decode_i_64(arr[7]),
      chapterTotal: dco_decode_i_64(arr[8]),
      prevChapterId: dco_decode_opt_box_autoadd_i_64(arr[9]),
      prevChapterTitle: dco_decode_opt_String(arr[10]),
      nextChapterId: dco_decode_opt_box_autoadd_i_64(arr[11]),
      nextChapterTitle: dco_decode_opt_String(arr[12]),
    );
  }

  @protected
  ComicBookmark dco_decode_comic_bookmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ComicBookmark(
      id: dco_decode_i_64(arr[0]),
      comicSourcePath: dco_decode_String(arr[1]),
      comicTitle: dco_decode_String(arr[2]),
      createdAt: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Library dco_decode_library(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Library(
      id: dco_decode_i_64(arr[0]),
      path: dco_decode_String(arr[1]),
      createdAt: dco_decode_i_64(arr[2]),
      updatedAt: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  LibraryScanStatus dco_decode_library_scan_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LibraryScanStatus(
      running: dco_decode_bool(arr[0]),
      startedAt: dco_decode_opt_box_autoadd_i_64(arr[1]),
      finishedAt: dco_decode_opt_box_autoadd_i_64(arr[2]),
      lastSummary: dco_decode_opt_box_autoadd_scan_summary(arr[3]),
      error: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  LibrarySourceStatus dco_decode_library_source_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return LibrarySourceStatus(
      configured: dco_decode_bool(arr[0]),
      path: dco_decode_String(arr[1]),
      exists: dco_decode_bool(arr[2]),
      isDir: dco_decode_bool(arr[3]),
      readable: dco_decode_bool(arr[4]),
      error: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  LibraryStorageStats dco_decode_library_storage_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LibraryStorageStats(
      totalSizeBytes: dco_decode_i_64(arr[0]),
      comicCount: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Bookmark> dco_decode_list_bookmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bookmark).toList();
  }

  @protected
  List<ComicBookmark> dco_decode_list_comic_bookmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_comic_bookmark).toList();
  }

  @protected
  List<Library> dco_decode_list_library(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_library).toList();
  }

  @protected
  List<PageInfo> dco_decode_list_page_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_page_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RawChapter> dco_decode_list_raw_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_raw_chapter).toList();
  }

  @protected
  List<RawComic> dco_decode_list_raw_comic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_raw_comic).toList();
  }

  @protected
  List<ReadingHistoryEntry> dco_decode_list_reading_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_reading_history_entry)
        .toList();
  }

  @protected
  List<SettingEntry> dco_decode_list_setting_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_setting_entry).toList();
  }

  @protected
  OpenChapterPayload dco_decode_open_chapter_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return OpenChapterPayload(
      comicSourcePath: dco_decode_String(arr[0]),
      chapterSourcePath: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ChapterContext? dco_decode_opt_box_autoadd_chapter_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_chapter_context(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ReadingProgress? dco_decode_opt_box_autoadd_reading_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_reading_progress(raw);
  }

  @protected
  ScanSummary? dco_decode_opt_box_autoadd_scan_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_scan_summary(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PageInfo dco_decode_page_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PageInfo(
      index: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      width: dco_decode_opt_box_autoadd_u_32(arr[2]),
      height: dco_decode_opt_box_autoadd_u_32(arr[3]),
    );
  }

  @protected
  PrefetchPagesPayload dco_decode_prefetch_pages_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PrefetchPagesPayload(
      chapterId: dco_decode_i_64(arr[0]),
      pageIndices: dco_decode_list_prim_u_32_strict(arr[1]),
    );
  }

  @protected
  RawChapter dco_decode_raw_chapter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return RawChapter(
      title: dco_decode_String(arr[0]),
      chapterIndex: dco_decode_i_64(arr[1]),
      sourcePath: dco_decode_String(arr[2]),
      sourceType: dco_decode_String(arr[3]),
      dateModified: dco_decode_i_64(arr[4]),
      pageCount: dco_decode_i_64(arr[5]),
      isRead: dco_decode_bool(arr[6]),
      lastPage: dco_decode_i_64(arr[7]),
      totalPages: dco_decode_i_64(arr[8]),
      sizeBytes: dco_decode_i_64(arr[9]),
    );
  }

  @protected
  RawComic dco_decode_raw_comic(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RawComic(
      title: dco_decode_String(arr[0]),
      sourcePath: dco_decode_String(arr[1]),
      sourceType: dco_decode_String(arr[2]),
      dateModified: dco_decode_i_64(arr[3]),
      chapterCount: dco_decode_i_64(arr[4]),
      readChapterCount: dco_decode_i_64(arr[5]),
      inProgressChapterCount: dco_decode_i_64(arr[6]),
      sizeBytes: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  ReadingHistoryEntry dco_decode_reading_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ReadingHistoryEntry(
      comicSourcePath: dco_decode_String(arr[0]),
      comicTitle: dco_decode_String(arr[1]),
      chapterTitle: dco_decode_String(arr[2]),
      chapterSourcePath: dco_decode_String(arr[3]),
      chapterId: dco_decode_i_64(arr[4]),
      lastPage: dco_decode_i_64(arr[5]),
      totalPages: dco_decode_i_64(arr[6]),
      isRead: dco_decode_bool(arr[7]),
      updatedAt: dco_decode_i_64(arr[8]),
    );
  }

  @protected
  ReadingProgress dco_decode_reading_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ReadingProgress(
      chapterId: dco_decode_i_64(arr[0]),
      lastPage: dco_decode_i_64(arr[1]),
      totalPages: dco_decode_i_64(arr[2]),
      isRead: dco_decode_bool(arr[3]),
    );
  }

  @protected
  RenderPagePayload dco_decode_render_page_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RenderPagePayload(
      chapterId: dco_decode_i_64(arr[0]),
      pageIndex: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  RenderedPage dco_decode_rendered_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RenderedPage(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      mime: dco_decode_String(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  SaveBookmarkPayload dco_decode_save_bookmark_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SaveBookmarkPayload(
      chapterId: dco_decode_i_64(arr[0]),
      page: dco_decode_i_64(arr[1]),
      note: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SaveProgressPayload dco_decode_save_progress_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SaveProgressPayload(
      chapterId: dco_decode_i_64(arr[0]),
      lastPage: dco_decode_i_64(arr[1]),
      totalPages: dco_decode_i_64(arr[2]),
      isRead: dco_decode_bool(arr[3]),
    );
  }

  @protected
  ScanSummary dco_decode_scan_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ScanSummary(
      comics: dco_decode_u_32(arr[0]),
      chapters: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  SettingEntry dco_decode_setting_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SettingEntry(
      key: dco_decode_String(arr[0]),
      valueJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  SortBy dco_decode_sort_by(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortBy.values[raw as int];
  }

  @protected
  SortDir dco_decode_sort_dir(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortDir.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Bookmark sse_decode_bookmark(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_chapterId = sse_decode_i_64(deserializer);
    var var_page = sse_decode_i_64(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_note = sse_decode_String(deserializer);
    return Bookmark(
      id: var_id,
      chapterId: var_chapterId,
      page: var_page,
      createdAt: var_createdAt,
      note: var_note,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChapterContext sse_decode_box_autoadd_chapter_context(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_chapter_context(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  OpenChapterPayload sse_decode_box_autoadd_open_chapter_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_open_chapter_payload(deserializer));
  }

  @protected
  PrefetchPagesPayload sse_decode_box_autoadd_prefetch_pages_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_prefetch_pages_payload(deserializer));
  }

  @protected
  ReadingProgress sse_decode_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_reading_progress(deserializer));
  }

  @protected
  RenderPagePayload sse_decode_box_autoadd_render_page_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_render_page_payload(deserializer));
  }

  @protected
  SaveBookmarkPayload sse_decode_box_autoadd_save_bookmark_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_save_bookmark_payload(deserializer));
  }

  @protected
  SaveProgressPayload sse_decode_box_autoadd_save_progress_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_save_progress_payload(deserializer));
  }

  @protected
  ScanSummary sse_decode_box_autoadd_scan_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scan_summary(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  ChapterContext sse_decode_chapter_context(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_i_64(deserializer);
    var var_comicId = sse_decode_i_64(deserializer);
    var var_comicSourcePath = sse_decode_String(deserializer);
    var var_chapterSourcePath = sse_decode_String(deserializer);
    var var_comicTitle = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_chapterIndex = sse_decode_i_64(deserializer);
    var var_chapterPosition = sse_decode_i_64(deserializer);
    var var_chapterTotal = sse_decode_i_64(deserializer);
    var var_prevChapterId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_prevChapterTitle = sse_decode_opt_String(deserializer);
    var var_nextChapterId = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_nextChapterTitle = sse_decode_opt_String(deserializer);
    return ChapterContext(
      chapterId: var_chapterId,
      comicId: var_comicId,
      comicSourcePath: var_comicSourcePath,
      chapterSourcePath: var_chapterSourcePath,
      comicTitle: var_comicTitle,
      title: var_title,
      chapterIndex: var_chapterIndex,
      chapterPosition: var_chapterPosition,
      chapterTotal: var_chapterTotal,
      prevChapterId: var_prevChapterId,
      prevChapterTitle: var_prevChapterTitle,
      nextChapterId: var_nextChapterId,
      nextChapterTitle: var_nextChapterTitle,
    );
  }

  @protected
  ComicBookmark sse_decode_comic_bookmark(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_comicSourcePath = sse_decode_String(deserializer);
    var var_comicTitle = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return ComicBookmark(
      id: var_id,
      comicSourcePath: var_comicSourcePath,
      comicTitle: var_comicTitle,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Library sse_decode_library(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return Library(
      id: var_id,
      path: var_path,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  LibraryScanStatus sse_decode_library_scan_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_startedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_finishedAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_lastSummary = sse_decode_opt_box_autoadd_scan_summary(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return LibraryScanStatus(
      running: var_running,
      startedAt: var_startedAt,
      finishedAt: var_finishedAt,
      lastSummary: var_lastSummary,
      error: var_error,
    );
  }

  @protected
  LibrarySourceStatus sse_decode_library_source_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_configured = sse_decode_bool(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_exists = sse_decode_bool(deserializer);
    var var_isDir = sse_decode_bool(deserializer);
    var var_readable = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return LibrarySourceStatus(
      configured: var_configured,
      path: var_path,
      exists: var_exists,
      isDir: var_isDir,
      readable: var_readable,
      error: var_error,
    );
  }

  @protected
  LibraryStorageStats sse_decode_library_storage_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalSizeBytes = sse_decode_i_64(deserializer);
    var var_comicCount = sse_decode_i_64(deserializer);
    return LibraryStorageStats(
      totalSizeBytes: var_totalSizeBytes,
      comicCount: var_comicCount,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Bookmark> sse_decode_list_bookmark(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Bookmark>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bookmark(deserializer));
    }
    return ans_;
  }

  @protected
  List<ComicBookmark> sse_decode_list_comic_bookmark(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ComicBookmark>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_comic_bookmark(deserializer));
    }
    return ans_;
  }

  @protected
  List<Library> sse_decode_list_library(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Library>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_library(deserializer));
    }
    return ans_;
  }

  @protected
  List<PageInfo> sse_decode_list_page_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PageInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_page_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RawChapter> sse_decode_list_raw_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RawChapter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_raw_chapter(deserializer));
    }
    return ans_;
  }

  @protected
  List<RawComic> sse_decode_list_raw_comic(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RawComic>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_raw_comic(deserializer));
    }
    return ans_;
  }

  @protected
  List<ReadingHistoryEntry> sse_decode_list_reading_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReadingHistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reading_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<SettingEntry> sse_decode_list_setting_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SettingEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_setting_entry(deserializer));
    }
    return ans_;
  }

  @protected
  OpenChapterPayload sse_decode_open_chapter_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comicSourcePath = sse_decode_String(deserializer);
    var var_chapterSourcePath = sse_decode_String(deserializer);
    return OpenChapterPayload(
      comicSourcePath: var_comicSourcePath,
      chapterSourcePath: var_chapterSourcePath,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ChapterContext? sse_decode_opt_box_autoadd_chapter_context(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_chapter_context(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReadingProgress? sse_decode_opt_box_autoadd_reading_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_reading_progress(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ScanSummary? sse_decode_opt_box_autoadd_scan_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_scan_summary(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PageInfo sse_decode_page_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    return PageInfo(
      index: var_index,
      name: var_name,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  PrefetchPagesPayload sse_decode_prefetch_pages_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_i_64(deserializer);
    var var_pageIndices = sse_decode_list_prim_u_32_strict(deserializer);
    return PrefetchPagesPayload(
      chapterId: var_chapterId,
      pageIndices: var_pageIndices,
    );
  }

  @protected
  RawChapter sse_decode_raw_chapter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_chapterIndex = sse_decode_i_64(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    var var_sourceType = sse_decode_String(deserializer);
    var var_dateModified = sse_decode_i_64(deserializer);
    var var_pageCount = sse_decode_i_64(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    var var_lastPage = sse_decode_i_64(deserializer);
    var var_totalPages = sse_decode_i_64(deserializer);
    var var_sizeBytes = sse_decode_i_64(deserializer);
    return RawChapter(
      title: var_title,
      chapterIndex: var_chapterIndex,
      sourcePath: var_sourcePath,
      sourceType: var_sourceType,
      dateModified: var_dateModified,
      pageCount: var_pageCount,
      isRead: var_isRead,
      lastPage: var_lastPage,
      totalPages: var_totalPages,
      sizeBytes: var_sizeBytes,
    );
  }

  @protected
  RawComic sse_decode_raw_comic(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    var var_sourceType = sse_decode_String(deserializer);
    var var_dateModified = sse_decode_i_64(deserializer);
    var var_chapterCount = sse_decode_i_64(deserializer);
    var var_readChapterCount = sse_decode_i_64(deserializer);
    var var_inProgressChapterCount = sse_decode_i_64(deserializer);
    var var_sizeBytes = sse_decode_i_64(deserializer);
    return RawComic(
      title: var_title,
      sourcePath: var_sourcePath,
      sourceType: var_sourceType,
      dateModified: var_dateModified,
      chapterCount: var_chapterCount,
      readChapterCount: var_readChapterCount,
      inProgressChapterCount: var_inProgressChapterCount,
      sizeBytes: var_sizeBytes,
    );
  }

  @protected
  ReadingHistoryEntry sse_decode_reading_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comicSourcePath = sse_decode_String(deserializer);
    var var_comicTitle = sse_decode_String(deserializer);
    var var_chapterTitle = sse_decode_String(deserializer);
    var var_chapterSourcePath = sse_decode_String(deserializer);
    var var_chapterId = sse_decode_i_64(deserializer);
    var var_lastPage = sse_decode_i_64(deserializer);
    var var_totalPages = sse_decode_i_64(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return ReadingHistoryEntry(
      comicSourcePath: var_comicSourcePath,
      comicTitle: var_comicTitle,
      chapterTitle: var_chapterTitle,
      chapterSourcePath: var_chapterSourcePath,
      chapterId: var_chapterId,
      lastPage: var_lastPage,
      totalPages: var_totalPages,
      isRead: var_isRead,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  ReadingProgress sse_decode_reading_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_i_64(deserializer);
    var var_lastPage = sse_decode_i_64(deserializer);
    var var_totalPages = sse_decode_i_64(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    return ReadingProgress(
      chapterId: var_chapterId,
      lastPage: var_lastPage,
      totalPages: var_totalPages,
      isRead: var_isRead,
    );
  }

  @protected
  RenderPagePayload sse_decode_render_page_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_i_64(deserializer);
    var var_pageIndex = sse_decode_u_32(deserializer);
    return RenderPagePayload(
      chapterId: var_chapterId,
      pageIndex: var_pageIndex,
    );
  }

  @protected
  RenderedPage sse_decode_rendered_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_mime = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return RenderedPage(
      bytes: var_bytes,
      mime: var_mime,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  SaveBookmarkPayload sse_decode_save_bookmark_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_i_64(deserializer);
    var var_page = sse_decode_i_64(deserializer);
    var var_note = sse_decode_opt_String(deserializer);
    return SaveBookmarkPayload(
      chapterId: var_chapterId,
      page: var_page,
      note: var_note,
    );
  }

  @protected
  SaveProgressPayload sse_decode_save_progress_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_i_64(deserializer);
    var var_lastPage = sse_decode_i_64(deserializer);
    var var_totalPages = sse_decode_i_64(deserializer);
    var var_isRead = sse_decode_bool(deserializer);
    return SaveProgressPayload(
      chapterId: var_chapterId,
      lastPage: var_lastPage,
      totalPages: var_totalPages,
      isRead: var_isRead,
    );
  }

  @protected
  ScanSummary sse_decode_scan_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comics = sse_decode_u_32(deserializer);
    var var_chapters = sse_decode_u_32(deserializer);
    return ScanSummary(comics: var_comics, chapters: var_chapters);
  }

  @protected
  SettingEntry sse_decode_setting_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_valueJson = sse_decode_String(deserializer);
    return SettingEntry(key: var_key, valueJson: var_valueJson);
  }

  @protected
  SortBy sse_decode_sort_by(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortBy.values[inner];
  }

  @protected
  SortDir sse_decode_sort_dir(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortDir.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bookmark(Bookmark self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.chapterId, serializer);
    sse_encode_i_64(self.page, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_String(self.note, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_chapter_context(
    ChapterContext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_chapter_context(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_open_chapter_payload(
    OpenChapterPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_open_chapter_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_prefetch_pages_payload(
    PrefetchPagesPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_prefetch_pages_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_reading_progress(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_render_page_payload(
    RenderPagePayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_render_page_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_save_bookmark_payload(
    SaveBookmarkPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_save_bookmark_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_save_progress_payload(
    SaveProgressPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_save_progress_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_scan_summary(
    ScanSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scan_summary(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_chapter_context(
    ChapterContext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.chapterId, serializer);
    sse_encode_i_64(self.comicId, serializer);
    sse_encode_String(self.comicSourcePath, serializer);
    sse_encode_String(self.chapterSourcePath, serializer);
    sse_encode_String(self.comicTitle, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.chapterIndex, serializer);
    sse_encode_i_64(self.chapterPosition, serializer);
    sse_encode_i_64(self.chapterTotal, serializer);
    sse_encode_opt_box_autoadd_i_64(self.prevChapterId, serializer);
    sse_encode_opt_String(self.prevChapterTitle, serializer);
    sse_encode_opt_box_autoadd_i_64(self.nextChapterId, serializer);
    sse_encode_opt_String(self.nextChapterTitle, serializer);
  }

  @protected
  void sse_encode_comic_bookmark(ComicBookmark self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.comicSourcePath, serializer);
    sse_encode_String(self.comicTitle, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_library(Library self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_library_scan_status(
    LibraryScanStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_opt_box_autoadd_i_64(self.startedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.finishedAt, serializer);
    sse_encode_opt_box_autoadd_scan_summary(self.lastSummary, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_library_source_status(
    LibrarySourceStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.configured, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.exists, serializer);
    sse_encode_bool(self.isDir, serializer);
    sse_encode_bool(self.readable, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_library_storage_stats(
    LibraryStorageStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.totalSizeBytes, serializer);
    sse_encode_i_64(self.comicCount, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bookmark(List<Bookmark> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bookmark(item, serializer);
    }
  }

  @protected
  void sse_encode_list_comic_bookmark(
    List<ComicBookmark> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_comic_bookmark(item, serializer);
    }
  }

  @protected
  void sse_encode_list_library(List<Library> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_library(item, serializer);
    }
  }

  @protected
  void sse_encode_list_page_info(
    List<PageInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_page_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(
      self is Uint32List ? self : Uint32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_raw_chapter(
    List<RawChapter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_raw_chapter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_raw_comic(
    List<RawComic> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_raw_comic(item, serializer);
    }
  }

  @protected
  void sse_encode_list_reading_history_entry(
    List<ReadingHistoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reading_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_setting_entry(
    List<SettingEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_setting_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_open_chapter_payload(
    OpenChapterPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.comicSourcePath, serializer);
    sse_encode_String(self.chapterSourcePath, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_chapter_context(
    ChapterContext? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_chapter_context(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_reading_progress(
    ReadingProgress? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_reading_progress(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_scan_summary(
    ScanSummary? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_scan_summary(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_page_info(PageInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_prefetch_pages_payload(
    PrefetchPagesPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.chapterId, serializer);
    sse_encode_list_prim_u_32_strict(self.pageIndices, serializer);
  }

  @protected
  void sse_encode_raw_chapter(RawChapter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.chapterIndex, serializer);
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.sourceType, serializer);
    sse_encode_i_64(self.dateModified, serializer);
    sse_encode_i_64(self.pageCount, serializer);
    sse_encode_bool(self.isRead, serializer);
    sse_encode_i_64(self.lastPage, serializer);
    sse_encode_i_64(self.totalPages, serializer);
    sse_encode_i_64(self.sizeBytes, serializer);
  }

  @protected
  void sse_encode_raw_comic(RawComic self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.sourceType, serializer);
    sse_encode_i_64(self.dateModified, serializer);
    sse_encode_i_64(self.chapterCount, serializer);
    sse_encode_i_64(self.readChapterCount, serializer);
    sse_encode_i_64(self.inProgressChapterCount, serializer);
    sse_encode_i_64(self.sizeBytes, serializer);
  }

  @protected
  void sse_encode_reading_history_entry(
    ReadingHistoryEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.comicSourcePath, serializer);
    sse_encode_String(self.comicTitle, serializer);
    sse_encode_String(self.chapterTitle, serializer);
    sse_encode_String(self.chapterSourcePath, serializer);
    sse_encode_i_64(self.chapterId, serializer);
    sse_encode_i_64(self.lastPage, serializer);
    sse_encode_i_64(self.totalPages, serializer);
    sse_encode_bool(self.isRead, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_reading_progress(
    ReadingProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.chapterId, serializer);
    sse_encode_i_64(self.lastPage, serializer);
    sse_encode_i_64(self.totalPages, serializer);
    sse_encode_bool(self.isRead, serializer);
  }

  @protected
  void sse_encode_render_page_payload(
    RenderPagePayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.chapterId, serializer);
    sse_encode_u_32(self.pageIndex, serializer);
  }

  @protected
  void sse_encode_rendered_page(RenderedPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.mime, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_save_bookmark_payload(
    SaveBookmarkPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.chapterId, serializer);
    sse_encode_i_64(self.page, serializer);
    sse_encode_opt_String(self.note, serializer);
  }

  @protected
  void sse_encode_save_progress_payload(
    SaveProgressPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.chapterId, serializer);
    sse_encode_i_64(self.lastPage, serializer);
    sse_encode_i_64(self.totalPages, serializer);
    sse_encode_bool(self.isRead, serializer);
  }

  @protected
  void sse_encode_scan_summary(ScanSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.comics, serializer);
    sse_encode_u_32(self.chapters, serializer);
  }

  @protected
  void sse_encode_setting_entry(SettingEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.valueJson, serializer);
  }

  @protected
  void sse_encode_sort_by(SortBy self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sort_dir(SortDir self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
